### ISSUE TITLE
[问题反馈] 佬，你好，为啥我的链接文章读取不到？

### ISSUE THREAD

**Issue by mrxie68** [willow-god/Friend-Circle-Lite#11]
https://www.brain-hole.org/friend.json其中第一个链接无法访问？

Run python run.py
爬虫已启用
正在从 https://www.brain-hole.org/friend.json 中获取，每个博客获取 5 篇文章
brain hole 的博客 https://www.brain-hole.org/ 无法访问
brain hole 发布了新文章：一键脚本自建 Frp 内网穿透访问家里 NAS 和软路由, 时间：2024-07-12 00:03
brain hole 发布了新文章：再启航，关东 8 日行（计划篇）, 时间：2024-06-03 02:19
brain hole 发布了新文章：我的 EDC 分享, 时间：2024-05-20 01:37
brain hole 发布了新文章：Instapaper 还是 Pocket？不妨试试这款新应用 — MarkMark, 时间：2024-04-27 02:[15](https://github.com/mrxie68/Friend-Circle-Lite/actions/runs/10095687012/job/27916437158#step:5:16)
brain hole 发布了新文章：逃离喧嚣，再游巴谷宿集, 时间：2024-04-18 15:32
数据处理完成
总共有 2 位朋友，其中 1 位博客可访问，1 位博客无法访问

**Comment by willow-god** [comment]
我看了一下，第一个站点没有rss订阅链接呀？类似于：https://blog.qyliu.top/atom.xml
我的项目判断支持三种格式：/rss2.xml，/atom.xml，/feed，但是我看了一下你的第一个地址好像都没有，你可以去试着联系一下让他加一下相关的功能。

**Comment by mrxie68** [comment]
原来如此 非常感谢  那个是index.xml

**Comment by willow-god** [comment]
emmm，index.xml当时好像没考虑上哈哈，不过添加起来不麻烦，你可以自己在这里按照上面一样的格式添加一下就行，我后面也抽时间更新一下

https://github.com/willow-god/Friend-Circle-Lite/blob/main/friend_circle_lite/get_info.py#L44-L87

**Comment by mrxie68** [comment]
好的 非常感谢
