### ISSUE TITLE
[功能建议]佬，我有个需求，不知道难不难实现？

### ISSUE THREAD

**Issue by mrxie68** [willow-god/Friend-Circle-Lite#12]
佬，我有个需求就是：在某个页面单独引用某个博主最近的文章，不知道这个难不难搞。希望能指点一二

**Comment by willow-god** [comment]
我没有听懂耶，可以具体一点嘛？

**Comment by mrxie68** [comment]
是这样的  假如我friend.json有10个友链，index里面现在使用 all.json是10个博友全部的文章。而我现在想在单个页面上获取到all.json里面某个或者某几个博友的文章。

**Comment by willow-god** [comment]
奥，虽然我没有实现，但是有all.json的数据了的话，使用js实现应该是不难的，可以加一个数组，如果为空则显示全部，如果有指定的则选择对应的友链

**Comment by mrxie68** [comment]
好的  谢谢  我研究研究

**Comment by willow-god** [comment]
https://github.com/willow-god/Friend-Circle-Lite/blob/main/main/fclite.js#L81-L90

这个部分是循环添加的位置，只需要在这个里面的开头判断一下，对应的标题是否在里面即可，标题为：article.avatar，可以在全局变量里写一个数组来进行限制

**Comment by willow-god** [comment]
> 是这样的 假如我friend.json有10个友链，index里面现在使用 all.json是10个博友全部的文章。而我现在想在单个页面上获取到all.json里面某个或者某几个博友的文章。

https://note.lius.me/6tn   密码：123456

这里我把那个 processArticles 函数重写了一下，应该能用，你可以参考一下试试

**Comment by mrxie68** [comment]
好的 感谢 感谢

**Comment by willow-god** [comment]
那我先把issue关闭了，如果还有什么需求可以继续说或者在我的博客里进行评论

**Comment by mrxie68** [comment]
好的 🤛🏼
