### ISSUE TITLE
[问题反馈]大佬，我的github action自动化脚本 在这个部分一直报错 不知道什么问题

### ISSUE THREAD

**Issue by imzql** [willow-god/Friend-Circle-Lite#13]
![f0d2f4411645416ea2605cb4d60a07f4.png](https://ice.frostsky.com/2024/08/10/f0d2f4411645416ea2605cb4d60a07f4.png)
如图 在执行自动化脚本 一直卡在这里 报错日志如上
我的友圈json 地址为 https://usj.cc/json/friends.json

**Comment by willow-god** [comment]
![image](https://github.com/user-attachments/assets/f7096bf7-085b-449f-bd2d-d3d1c6de6d4a)
你是点的这个重新运行嘛？

**Comment by imzql** [comment]
是的 手动运行

**Comment by imzql** [comment]
重新试了几遍 好像可以了 参数填错了 谢谢

**Comment by willow-god** [comment]
> 重新试了几遍 好像可以了 参数填错了 谢谢

好的，有问题再联系
