### ISSUE TITLE
[问题反馈]大佬您好，反馈一个问题

### ISSUE THREAD

**Issue by imzql** [willow-god/Friend-Circle-Lite#14]
我在使用您[Friend-Circle-Lite](https://github.com/willow-god/Friend-Circle-Lite)项目时，一些境内的博客屏蔽了非大陆访问，导致抓不到他们的rss文章，请问这种有什么方法可以解决

**Comment by willow-god** [comment]
> 我在使用您[Friend-Circle-Lite](https://github.com/willow-god/Friend-Circle-Lite)项目时，一些境内的博客屏蔽了非大陆访问，导致抓不到他们的rss文章，请问这种有什么方法可以解决

这个没办法解决，只能通过自部署解决，如果你有服务器的话我昨天给了自部署的教程，你感兴趣可以看看

**Comment by imzql** [comment]
感谢回复 等有空研究一下 请问后续会不会提供docker方式部署呢

**Comment by willow-god** [comment]
大概率不会，因为没必要😂😂😂感觉部署起来并不困难，依赖的python包也不多，很多都是py自带的

**Comment by willow-god** [comment]
> 感谢回复 等有空研究一下 请问后续会不会提供docker方式部署呢

并且因为是专注于轻量化，我定时任务都是用linux自带的cronlab实现的，并没有用python实现定时，所以不太好实现docker（主要是因为不太熟悉docker操作QAQ），但是使用cronlab的方式修改定时抓取的时间和内容都会很方便，建议搭配面板类工具使用如宝塔，1p等等，这些都有现成的定时任务，只需要简单的添加一下就能实现。
![image](https://github.com/user-attachments/assets/66a82c01-0d5d-4030-a8bf-7ff35d05e6fd)
这里是1panel定时任务的位置，宝塔的话在readme里面有写
