### ISSUE TITLE
[问题反馈] 排序失败

### ISSUE THREAD

**Issue by CCKNBC** [willow-god/Friend-Circle-Lite#15]
Actions 屡次运行失败，[仓库链接](https://github.com/ccknbc-actions/Friend-Circle-Lite)  本地虚拟环境捕获到如下错误

```bash

......

总共有 79 位朋友，其中 36 位博客可访问，43 位博客无法访问
Traceback (most recent call last):
  File "d:\GitHub\Friend-Circle-Lite\run.py", line 25, in <module>
    sorted_result = sort_articles_by_time(result)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\GitHub\Friend-Circle-Lite\friend_circle_lite\get_info.py", line 294, in sort_articles_by_time
    sorted_articles = sorted(
                      ^^^^^^^
  File "d:\GitHub\Friend-Circle-Lite\friend_circle_lite\get_info.py", line 296, in <lambda>
    key=lambda x: datetime.strptime(x['created'], '%Y-%m-%d %H:%M'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python-3.12\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python-3.12\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d %H:%M'
```

此外，有几点想法：

1. 关于环境变量，可使用 `GITHUB_TOKEN` 替代 `PAT_TOKEN ` ，少创建一个是一个，系统默认提供一个
2. 由于 json 等才是我们需要的生成产物，是否应该推送到其他分支，否则后续更新其实太多无意义提交，fork 时 fork main分支即可
3. Vercel 可提供 `vercel.json`， CF Paged 可提供 `_redirects` 直接重定向 all.json，[例如](https://friend-circle-lite.ccknbc.cc)

**Comment by willow-god** [comment]
第一个问题，我感觉是因为某个友链的时间不符合标准，你可以尝试在那个函数使用之前打印出来看看是不是哪个友链的时间信息为空导致无法处理，如果能找到，请将对应友链链接发给我我尝试本地测试一下，然后适配一下

至于下面的，这个你可以自行修改，我这里没有使用默认的是为了更加精确的权限和有效期设置，我并没有使用默认的测试，也不知道可不可行，你可以试试看，然后后面两个，第一个的话，应该没有夺少额外提交呀，自动提交本身需要的就是json文件，至于自己的更新，我认为应该不会更新多少，毕竟友链信息是放到了json文件中，不需要我们去更新仓库

cf重定向的话，我感觉有点麻烦，不太熟悉其中的操作，目前的主页是放了一个友链朋友圈页面，感觉不算没用🫢

这个项目本身就是一个简单的定时任务脚本，可以自行根据要求进行更改的

**Comment by willow-god** [comment]
[421c3f5](https://github.com/willow-god/Friend-Circle-Lite/commit/421c3f53c8117e6eb8249ac5d86a8623ddbfc8f8)

在最近的更新中已经解决时间不标准导致的无法排序的问题，请重新复刻后配置

至于下面两个，我会抽时间去学习一下

我先把这个issue关了，如果有什么问题可以继续提问

**Comment by CCKNBC** [comment]
> [421c3f5](https://github.com/willow-god/Friend-Circle-Lite/commit/421c3f53c8117e6eb8249ac5d86a8623ddbfc8f8)
> 
> 在最近的更新中已经解决时间不标准导致的无法排序的问题，请重新复刻后配置
> 
> 至于下面两个，我会抽时间去学习一下
> 
> 我先把这个issue关了，如果有什么问题可以继续提问

https://github.com/ccknbc-actions/Friend-Circle-Lite/tree/pages 

拉取新代码后部署成功，演示站js加载成功
