### ISSUE TITLE
[问题反馈] 我想询问一下

### ISSUE THREAD

**Issue by Catwb** [willow-god/Friend-Circle-Lite#17]
<img width="404" alt="屏幕截图 2024-09-15 095640" src="https://github.com/user-attachments/assets/6196d905-1080-42f8-aeba-ef71e9c92dae">

我想询问一下为什么会出现这样的情况

**Comment by willow-god** [comment]
我看了一下你的json的格式，不太对呀，你可以看看我的：

https://blog.liushen.fun/friend.json

![image](https://github.com/user-attachments/assets/ed1bdc55-e6aa-4722-8555-fd70e3ba305a)

他是没有前面的标签值的，但是你的有标签值，你可以改改你的json生成的代码。

**Comment by Catwb** [comment]
好的，原来是这个原因，感谢，已经解决了

**Comment by willow-god** [comment]
> 好的，原来是这个原因，感谢，已经解决了

没关系，有问题再问，那这个issue我先关闭了
