### ISSUE TITLE
[问题反馈]关于RSS爬取

### ISSUE THREAD

**Issue by Catwb** [willow-god/Friend-Circle-Lite#18]
请问一下爬取功能是按照rss排列的顺序来抓取文章的么，某博客的最新文章（2024年）在rss的最下面，但是抓取时却抓取了rss最上面的那一篇（2022年）

**Comment by willow-god** [comment]
嘶，真没考虑这个问题，我设置的是从上往下抓取的，且取前面的几个
要不留一下那个rss的地址，我找时间处理一下然后测试用

**Comment by Catwb** [comment]
[peterjxl.com/rss.xml](https://www.peterjxl.com/rss.xml)

---

还有一个问题是我用您的嵌入代码，然后fc lite地址填了我自己的，但是加载不出来是为什么
（blog和fc lite都在cloudflare上）

**Comment by willow-god** [comment]
> [peterjxl.com/rss.xml](https://www.peterjxl.com/rss.xml)
> 
> 还有一个问题是我用您的嵌入代码，然后fc lite地址填了我自己的，但是加载不出来是为什么 （blog和fc lite都在cloudflare上）

留一下你用的代码，或者说出现错误的页面的地址，要不然我也不知道怎么判断呀

**Comment by Catwb** [comment]
没事了，我发现又可以加载出来了😂，是我操作失误了
不过这个代码好像与[pjax](https://github.com/next-theme/pjax)不兼容（？），在其他进入fc页面的时候是什么也没有，要在fc页面刷新才能有加载更多等

刷新前（从其他页面进入）：
![Screenshot_2024-09-22-14-48-21-83_a252b927494330c](https://github.com/user-attachments/assets/d5c15ecc-5632-487a-a3ef-581b0a09453d)

刷新后：
![Screenshot_2024-09-22-14-49-35-57_a252b927494330c](https://github.com/user-attachments/assets/7cfc2200-8544-4d31-9c01-dd5af76cc14c)

**Comment by willow-god** [comment]
这个pjax的适配我没办法，毕竟每个主题都不一样，但是我的博客也是开了pjax的，可以适配。

你可以看看你的主题怎么加载pjax的，按理说就调用一下js代码里面那个函数就行。

**Comment by Catwb** [comment]
我尝试吧😂

**Comment by willow-god** [comment]
b95ad11

最新的更新应该已经修复了你说的那个由于倒序导致的问题，你可以测试一下
