### ISSUE TITLE
[⭐页面展示]如果你成功部署了，且想展示你的页面，欢迎留言！

### ISSUE THREAD

**Issue by willow-god** [willow-god/Friend-Circle-Lite#20]
🤤如果你成功部署了，且想展示你的页面，欢迎在这个issue下留言！

**Comment by yeminxi** [comment]
我我我（显眼包）https://fc.ymxapi.us.kg

**Comment by willow-god** [comment]
> 按照自己想法重写了前端代码、改造部分后端代码（每个好友用数组形式存是否有点奇怪）
> 
> [cworld0.com/links](https://cworld0.com/links)

确实好看多了哈哈，一个月后我打算重写一下代码，现在这个随着代码量增多有点丑陋了😂😂😂到时候参考一下老哥的！

**Comment by cworld1** [comment]
@willow-god 还好还好，代码不算臃肿，自己改一改就能用。而且我这前端改成ts代码了，除了打包成npm包外没啥参考价值

**Comment by Peter267** [comment]
做好啦，来看看：
https://fcircle.zeabur.app

**Comment by JLinMr** [comment]
> 按照自己想法重写了前端代码、改造部分后端代码（每个好友用数组形式存是否有点奇怪）
> 
> https://cworld0.com/links

嘿嘿，我这个界面就是借鉴的你的样式布局 https://blog.ruom.top/fcircle
