### ISSUE TITLE
[问题反馈]关于rss爬取-2

### ISSUE THREAD

**Issue by Catwb** [willow-god/Friend-Circle-Lite#21]
在新版本的fcl确实是按照了时间顺序
不过按照时间排序后我发现输出时间比rss内时间多了一天
![Screenshot_2024-09-30-23-09-15-23_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/user-attachments/assets/4daeb1fb-0627-42f1-810a-fa2ea44a920b)

![Screenshot_2024-09-30-23-09-45-14_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/user-attachments/assets/7fc9011b-fe97-4743-8178-56e63032f043)

**Comment by willow-god** [comment]
> 在新版本的fcl确实是按照了时间顺序 不过按照时间排序后我发现输出时间比rss内时间多了一天 

问题存在，是历史遗留问题，之前为了时区同步，加了八小时，之后通过设置时区解决了，但是忘记删掉了，目前已经修复，详见：

 [21a2ce4](https://github.com/willow-god/Friend-Circle-Lite/commit/21a2ce44f9f068cb730b3acac8f71fdc3004215e)

**Comment by willow-god** [comment]
不对，我发现这个时间是正常的，是因为上面他发布时间是格林尼治标准时间，也就是世界协调时间，是和我们有八个小时的差距的，所以会显示略后，不过之前的代码确实都是没有判断时区就直接加八了，目前准备改改代码，使其根据时区转换时间。

**Comment by Catwb** [comment]
喔，这样
