### ISSUE TITLE
[问题反馈] 获取不到 friend.json

### ISSUE THREAD

**Issue by uuanqin** [willow-god/Friend-Circle-Lite#31]
Hello Liushen! 

最近发现爬虫获取不到 friend.json 文件。但是正常访问 https://blog.uuanqin.top/friend.json 是可以的。这是咋回事呢？

![image](https://github.com/user-attachments/assets/da28cb00-7a98-4fb5-ad84-92bb041de63c)

**Comment by willow-god** [comment]
![image](https://github.com/user-attachments/assets/8f99e932-934a-4d1c-ac6d-a7945d8a24a7)
你应该做了分流导致国外到github page了，但是github page似乎没有这个文件导致无法抓取到，你可以通过全局代理测试检查一下

国内环境我这边测试是正常的

**Comment by willow-god** [comment]
https://lius.me/https://blog.uuanqin.top/friend.json

可以通过这个国外的代理检查你的国外线路是否正常

**Comment by uuanqin** [comment]
是的。我刚刚才解决的。我把文件换个地方存就正常了。

至于404的原因我还得自己排查下。感谢解答！
