### ISSUE TITLE
[问题反馈] 一些文章的标题显示乱码

### ISSUE THREAD

**Issue by uuanqin** [willow-god/Friend-Circle-Lite#32]
圣诞快乐🎄！~~（没错我又来了😁）~~

最近订阅了一个博主，发现拉取他的文章标题总是乱码。这是怎么回事呀？

![image](https://github.com/user-attachments/assets/9a5970a6-10aa-40a0-8172-fa262a5f896b)

那位博主的博客： https://blog.codingnow.com/
链接： https://blog.uuanqin.top/pages/friend_circle/

**Comment by willow-god** [comment]
我这里显示已经修复，是编码的问题，原先强制了UTF-8，最新版采用了自动获取编码，可以更新查看修复情况
